"""
This file is autogenerated to lazily import symbols from '__init__.py'.

Do NOT edit manually.
"""

import importlib

_lazy_imports = {
    "Baseline": ("vlm_gist.core.baseline", "Baseline"),
    "StructuredDescription": ("vlm_gist.core.structured_description", "StructuredDescription"),
    "Detection": ("vlm_gist.core.detection", "Detection"),
    "Validation": ("vlm_gist.core.validation", "Validation"),
    "VlmGist": ("vlm_gist.core.vlm_gist", "VlmGist"),
    "LabelMatching": ("vlm_gist.core.label_matching", "LabelMatching"),
    "test_image_path": ("vlm_gist.core.common", "test_image_path"),
}

_import_cache = {}

def __getattr__(name):
    if name in _import_cache:
        return _import_cache[name]
    if name in _lazy_imports:
        module_name, attr_name = _lazy_imports[name]
        module = importlib.import_module(module_name)
        attr = getattr(module, attr_name)
        _import_cache[name] = attr
        return attr
    raise AttributeError(f"Module '{__name__}' has no attribute '{name}'.")

def __dir__():
    return sorted(list(globals().keys()) + list(_lazy_imports.keys()))
